const i18Obj = {
  'en': {
    'description': 'Description',
    'interier': 'Interier',
    'dimentions': 'Dimentions',
    'contacts': 'Contacts',
    'sofa': 'Sofa table for computer.',
    'optim': 'Optimized for wired devices.',
    'li1': '4 USB 3.0 ports.',
    'li2': '5 meters cable USB 3.0.',
    'li3': 'Integrated cable management.',
    'li4': 'Small pockets.',
    'li5': 'Upholstery material - leatherette.',
    'rub': 'rub.',
    'more': 'Learn more',
    'n1-title': 'Play your favorite games while sitting on the couch.',
    'n1-text1': 'This patented system uses only the finest materials such as leather and microfiber, allowing you to control your computer from your sofa in the most comfortable environment.',
    'n1-text2': 'Couchmaster is a great platform for long hours of gaming or ergonomic work using your TV or projector.',
    'n1-text3': 'Up to 4 devices can be connected to the built-in USB 3.0 connectors (for example, a mouse, keyboard, headphones, etc.).    The system works without additional power supplies.',
    'n1-text4': 'The Couchmaster connects to your computer via a 5m USB 3.0 cable (can be extended up to 10m if needed).',
    'n2-title': 'Excellent ergonomics.',
    'n2-text1': '“From a health point of view, I can say that Couchmaster offers the best option for ergonomic work at a computer or laptop.',
    'n2-text2': 'Large pillows allow you to relieve stress on the muscles of the shoulder and neck, which helps prevent muscle spasms.',
    'n2-text3': '- Rolland Kellerbach, physiotherapist, Cologne - Delbruck, Germany.',
    'n3-title': 'Cable management.',
    'n3-text1': 'All excess wires are easily removed inside the countertop.',
    'n3-text2': 'Any peripheral devices can be connected as you like.',
    'n3-text3': 'Couchmaster is equally comfortable for both right-handers and left-handers.    You can also attach the keyboard to the tabletop using the included Velcro tape.',
    'order': 'Order Couchmaster® CYCON now',
    'in interier': 'Couchmaster® CYCON in interier',
    'dim': 'Dimentions Couchmaster® CYCON',
    'payment': 'Payment',
    'cards': 'Cards Visa, MasterCard, Mir.',
    'delivery': 'Delivery by transport companies',
    'wallets': 'Electronic wallets Yandex, Qiwi, Webmoney.',
    'cod': 'C.O.D.',
    'sdec': 'SDEC',
    'lines': 'Business Lines',
  },
  'ru': {
    'description': 'Описание',
    'interier': 'Интерьер',
    'dimentions': 'Размеры',
    'contacts': 'Контакты',
    'sofa': 'Диванный стол для компьютера.',
    'optim': 'Оптимизирован для проводных устройств.',
    'li1': '4 порта USB 3.0.',
    'li2': '5-ти метровый кабель USB 3.0.',
    'li3': 'Встроенный кабель-менеджмент.',
    'li4': 'Карманы для мелочей.',
    'li5': 'Материал обивки пуфов - кожзам.',
    'rub': 'руб.',
    'more': 'Подробнее',
    'n1-title': 'Играйте в любимые игры сидя на диване.',
    'n1-text1': 'В этой запатентованной системе используются только лучшие материалы, такие как кожа и микрофибра, что позволяет вам в максимально комфортных условиях управлять вашим компьютером прямо с дивана.',
    'n1-text2': 'Couchmaster - отличная платформа для долгих игр или эргономичной работы с использованием вашего телевизора или проектора.',
    'n1-text3': 'К встроенным USB 3.0 разъемам можно подключать до 4 устройств (например, мышку, клавиатуру, наушники и т.д.). Система работает без дополнительных источников питания.',
    'n1-text4': 'Couchmaster соединяется с вашим компьютером с помощью 5-ти метрового USB 3.0 кабеля (при необходимости может быть удлинен до 10 метров).',
    'n2-title': 'Отличная эргономика.',
    'n2-text1': '“С точки зрения здоровья, я могу сказать, что Couchmaster предлагает лучший вариант для эргономичной работы за компьютером или ноутбуком.',
    'n2-text2': 'Большие подушки позволяют снять нагрузку с мышц плеча и шеи, что помогает предотвратить мышечные спазмы."',
    'n2-text3': '- Ролланд Келлербах, физиотерапевт, Кельн - Дельбрук, Германия.',
    'n3-title': 'Кабель-менеджмент.',
    'n3-text1': 'Все лишние провода легко убираются внутрь столешницы. Любые периферийные устройства могут подсоединяться так, как вам удобно.',
    'n3-text2': 'Couchmaster одинаково удобен как для правшей, так и для левшей.',
    'n3-text3': 'Также вы можете закрепить клавиатуру на столешнице с помощью Velcro-ленты, которая идет в комплекте.',
    'order': 'Заказать Couchmaster® CYCON сейчас',
    'in interier': 'Couchmaster® CYCON в интерьере',
    'dim': 'Габариты Couchmaster® CYCON',
    'cards': 'Карты Visa, MasterCard, Мир.',
    'payment': 'Оплата',
    'delivery': 'Доставка транспортными компаниями',
    'wallets': 'Электронные кошельки Яндекс, Qiwi, Webmoney.',
    'cod': 'Наложенный платеж.',
    'sdec': 'СДЭК',
    'lines': 'Деловые линии',
  }
}
export default i18Obj;
